language: c

notifications:
  email: false

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

before_script:
  - sudo pip install pytest

script:
  - make CC=${CC} LD=${CC} OPTIM=NONE
  - ./sigfox_callback.out -p 8000 &
  - PID=$!
  - make test
  - kill ${PID}