language: c

notifications:
  email: false

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

before_script:
  - pip install pytest

script:
  - make CC=${CC} LD=${CC} OPTIM=NONE
  - PID=$!
  - make test
  - kill ${PID}